project_id = "opkqdwwmgnbqbtlrybxm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

# [db.vault]
# secret_key = "env(SECRET_VALUE)"

[db.migrations]
enabled = true
schema_paths = ["supabase/migrations"]

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[db.network_restrictions]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
allowed_cidrs_v6 = ["::/0"]

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets.property_images]
public = true
file_size_limit = "10MiB"
allowed_mime_types = ["image/png", "image/jpeg"]

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true  # Added to match remote
secure_password_change = false
max_frequency = "1m0s"  # Added to match remote
otp_length = 6
otp_expiry = 3600

[auth.external.google]
enabled = false  # Updated from true
client_id = ""  # Updated from existing value
secret = ""  # Updated from env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)
redirect_uri = "http://localhost:3000"  # Updated from 5173
skip_nonce_check = false

[edge_runtime]
enabled = true
policy = "oneshot"
inspector_port = 8083
deno_version = 1

[analytics]
enabled = true
port = 54327
backend = "postgres"